# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: objective-c
xcode_workspace: Example/SSTSwitch.xcworkspace #3
xcode_scheme: SSTSwitch-Example #4
xcode_sdk: iphonesimulator12.2
